### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/blog-derecho#1]
Qué sucede con el README?
está con extensión .html y tiene codigo de la página, por lo que se muestra en a página inicial
los archivos readme son del tipo Markdown por lo que su extension debería ser .md

**Comment by Itzli2000** [comment]
En un rato modifico el readme, primero estoy empezando a estructurar bien el proyecto y al final modifico el archivo reademe.

**Comment by Itzli2000** [comment]
Readme modificado, solo falta agregar la información.
Se cierra issue.
